{% set version = "1.0.8" %}

package:
  name: resonate
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/resonATe/resonATe-{{ version }}.tar.gz
  sha256: 6fabb0919908abf69b4fcb5054413588db5ede8f53ad3bfbd909aa931587d382

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
    - pandas
    - numpy
    - sphinx
    - geopy
    - simplejson
    - colorama
    - plotly
    - nbconvert
  run:
    - python
    - pandas
    - numpy
    - sphinx
    - geopy
    - simplejson
    - pytest
    - colorama
    - plotly
    - nbconvert

test:
  requires:
    - pytest
  imports:
    - resonate

about:
  home: https://gitlab.oceantrack.org/otndc/resonate
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: Acoustic telemetry analysis and processing toolkit in Python
  description: |
    resonATe is the Ocean Tracking Network's acoustic telemetry
    analysis toolkit. It can be used to filter, compress, visualize
    and analyze acoustic detection extracts from OTN and other marine
    telemetry data.
  doc_url: http://resonate.readthedocs.io/
  dev_url: https://gitlab.oceantrack.org/otndc/resonate

extra:
  recipe-maintainers:
    - alexetnunes
