{% set version = "1.0.9" %}

package:
  name: resonate
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/resonATe/resonATe-{{ version }}.tar.gz
  sha256: e3359e2628e4efdfd4f8cb204f7fc4e0d28f100d268e37da73028e898992a64f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=2.7
    - pip
    - pandas
    - numpy
    - sphinx
    - geopy
    - simplejson
    - colorama
    - plotly
    - nbconvert
  run:
    - python >=2.7
    - pandas
    - numpy
    - sphinx
    - geopy
    - simplejson
    - pytest
    - colorama
    - plotly
    - nbconvert

test:
  requires:
    - pytest
  imports:
    - resonate

about:
  home: https://gitlab.oceantrack.org/otndc/resonate
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Acoustic telemetry analysis and processing toolkit in Python
  description: |
    resonATe is the Ocean Tracking Network's acoustic telemetry
    analysis toolkit. It can be used to filter, compress, visualize
    and analyze acoustic detection extracts from OTN and other marine
    telemetry data.
  doc_url: http://resonate.readthedocs.io/
  dev_url: https://gitlab.oceantrack.org/otndc/resonate

extra:
  recipe-maintainers:
    - alexetnunes
