{% set version = "1.0.2" %}

package:
  name: resonate
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/resonATe/resonATe-{{ version }}.tar.gz
  sha256: 699f6a343b5f5b90e5dc4e0a00cf71ce1b12e0e6d00bffc6f0a5c2ff1ac2d5ce

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - pandas
    - numpy
    - sphinx
    - geopy
    - simplejson
    - colorama
    - plotly
    - nbconvert
  run:
    - python
    - pandas
    - numpy
    - sphinx
    - geopy
    - simplejson
    - pytest
    - colorama
    - plotly
    - nbconvert

test:
  requires:
    - pytest
  imports:
    - resonate

about:
  home: https://gitlab.oceantrack.org/otndc/resonate
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: 'Acoustic telemetry analysis and processing toolkit in Python'
  description: |
    resonATe is the Ocean Tracking Network's acoustic telemetry
    analysis toolkit. It can be used to filter, compress, visualize
    and analyze acoustic detection extracts from OTN and other marine
    telemetry data.
  doc_url: http://resonate.readthedocs.io/
  dev_url: https://gitlab.oceantrack.org/otndc/resonate

extra:
  recipe-maintainers:
    - alexetnunes
