{% set name = "resonATe" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 09edbafbd0c843c2e9c4cf8b14e45218e2fc2148f8545c9c8a1b42dcb24ca5ae

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - pandas
    - numpy
    - sphinx
    - geopy
    - simplejson
    - colorama
    - plotly
    - nbconvert
  run:
    - python
    - pandas
    - numpy
    - sphinx
    - geopy
    - simplejson
    - pytest
    - colorama
    - plotly
    - nbconvert

test:
  requires:
    - pytest
  imports:
    - resonate

about:
  home: https://gitlab.oceantrack.org/otndc/resonate
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: 'Acoustic telemetry analysis and processing toolkit in Python'
  description: |
    resonATe is the Ocean Tracking Network's acoustic telemetry
    analysis toolkit. It can be used to filter, compress, visualize
    and analyze acoustic detection extracts from OTN and other marine
    telemetry data.
  doc_url: http://resonate.readthedocs.io/
  dev_url: https://gitlab.oceantrack.org/otndc/resonate

extra:
  recipe-maintainers:
    - alexetnunes
